#!/usr/bin/env python3
"""Curate a 200-passage Spanish guided-learning course.

The script reads every ``top_verb_video`` row, reconstructs the transcript
passage, asks OpenAI to judge its learning quality, and writes the selected
course to ``learning_passage``.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import logging
import math
import os
import re
import shutil
import ssl
import subprocess
import sys
import time
import unicodedata
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Iterable


LOGGER = logging.getLogger("build_guided_learning_passages")
DEFAULT_LANGUAGE = "es"
DEFAULT_MODEL = "gpt-5-mini"
DEFAULT_PAGE_SIZE = 1000
DEFAULT_SEGMENT_VIDEO_CHUNK_SIZE = 100
DEFAULT_COURSE_SIZE = 200
COURSE_TARGETS = {
    "beginner": 45,
    "lower intermediate": 65,
    "upper intermediate": 55,
    "advanced": 35,
}
LEVEL_ORDER = ["beginner", "lower intermediate", "upper intermediate", "advanced"]
LEVEL_INDEX = {level: index for index, level in enumerate(LEVEL_ORDER)}
MAX_PASSAGES_PER_VERB = 8
MAX_PASSAGES_PER_VIDEO = 3
MAX_MODEL_TEXT_CHARS = 1800
CREATE_TABLES_SQL = """
create table if not exists learning_passage (
  id bigint generated by default as identity primary key,
  language text not null default 'es',
  top_verb_video_id bigint null,
  video_id bigint not null,
  verb_id bigint null,
  level_band text not null,
  rank_order integer not null,
  skill_focus text not null default 'verb forms',
  start_segment_id integer null,
  end_segment_id integer null,
  quality_score numeric null,
  interest_score integer null,
  clarity_score integer null,
  proper_noun_load integer null,
  learner_value_score integer null,
  estimated_cefr text null,
  verb_tier integer null,
  word_count integer null,
  passage_preview text null,
  evaluator_model text null,
  evaluator_json jsonb null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists learning_passage_language_rank_idx
on learning_passage(language, rank_order);

create unique index if not exists learning_passage_top_verb_video_idx
on learning_passage(top_verb_video_id)
where top_verb_video_id is not null;

create table if not exists user_learning_passage_progress (
  id bigint generated by default as identity primary key,
  user_id text not null,
  language text not null default 'es',
  source_key text not null,
  passage_id bigint null,
  status text not null,
  confidence integer null,
  started_at timestamptz null,
  completed_at timestamptz null,
  skipped_at timestamptz null,
  updated_at timestamptz not null default now(),
  unique (user_id, source_key)
);
"""


COMMON_VERB_TIERS = {
    "ser": 1,
    "estar": 1,
    "tener": 1,
    "haber": 1,
    "ir": 1,
    "hacer": 1,
    "decir": 1,
    "poder": 1,
    "querer": 1,
    "saber": 1,
    "ver": 1,
    "dar": 1,
    "poner": 1,
    "venir": 1,
    "deber": 2,
    "llevar": 2,
    "llegar": 2,
    "pasar": 2,
    "quedar": 2,
    "hablar": 2,
    "pensar": 2,
    "seguir": 2,
    "encontrar": 2,
    "salir": 2,
    "volver": 2,
    "tomar": 2,
    "creer": 2,
    "dejar": 2,
    "mirar": 2,
    "sentir": 2,
    "vivir": 2,
    "trabajar": 2,
    "comer": 2,
    "comprar": 2,
    "entender": 2,
    "conocer": 2,
    "aprender": 2,
    "empezar": 2,
    "necesitar": 2,
    "usar": 2,
    "gustar": 2,
}


@dataclass(frozen=True)
class Verb:
    id: Any
    name: str


@dataclass(frozen=True)
class Channel:
    channel_id: str
    difficulty: str | None
    language: str | None


@dataclass(frozen=True)
class Video:
    id: Any
    video_id: str | None
    channel_id: str
    difficulty: str | None
    title: str | None


@dataclass(frozen=True)
class Segment:
    segment_id: int
    text: str
    video_id: Any


@dataclass(frozen=True)
class TopVerbVideo:
    id: Any
    video_id: Any
    verb_id: Any
    count: int
    difficulty: str | None
    start: int
    end: int


@dataclass(frozen=True)
class Candidate:
    top_verb_video_id: Any
    video_id: Any
    verb_id: Any
    verb: str
    verb_tier: int
    verb_count: int
    video_title: str
    db_difficulty: str
    start_segment_id: int
    end_segment_id: int
    passage_text: str
    passage_preview: str
    word_count: int
    proper_noun_guess_count: int


@dataclass(frozen=True)
class Judgement:
    eligible: bool
    interest_score: int
    clarity_score: int
    proper_noun_load: int
    learner_value_score: int
    estimated_level_band: str
    estimated_cefr: str
    rejection_reason: str
    short_rationale: str


@dataclass(frozen=True)
class JudgedCandidate:
    candidate: Candidate
    judgement: Judgement
    course_band: str
    quality_score: float


class SupabaseRestClient:
    def __init__(self, url: str, service_role_key: str, page_size: int) -> None:
        self.base_url = url.rstrip("/")
        self.page_size = page_size
        self.ssl_context = create_ssl_context()
        self.base_headers = {
            "apikey": service_role_key,
            "Authorization": f"Bearer {service_role_key}",
            "Content-Type": "application/json",
        }

    def fetch_all(
        self,
        table: str,
        *,
        select: str = "*",
        filters: dict[str, str] | None = None,
        order: str | None = None,
    ) -> list[dict[str, Any]]:
        rows: list[dict[str, Any]] = []
        offset = 0
        while True:
            query = {"select": select}
            if filters:
                query.update(filters)
            if order:
                query["order"] = order
            batch = self._request_json(
                "GET",
                table,
                query=query,
                headers={
                    "Range-Unit": "items",
                    "Range": f"{offset}-{offset + self.page_size - 1}",
                },
            )
            if not isinstance(batch, list):
                raise RuntimeError(f"Expected list response from {table}")
            rows.extend(batch)
            if len(batch) < self.page_size:
                return rows
            offset += self.page_size

    def delete(self, table: str, *, filters: dict[str, str]) -> None:
        self._request_json("DELETE", table, query=filters, headers={"Prefer": "return=minimal"})

    def insert(self, table: str, rows: list[dict[str, Any]], *, chunk_size: int = 500) -> None:
        for start in range(0, len(rows), chunk_size):
            self._request_json(
                "POST",
                table,
                body=rows[start : start + chunk_size],
                headers={"Prefer": "return=minimal"},
            )

    def _request_json(
        self,
        method: str,
        table: str,
        *,
        query: dict[str, str] | None = None,
        body: Any | None = None,
        headers: dict[str, str] | None = None,
    ) -> Any:
        query_string = urllib.parse.urlencode(query or {}, safe="(),.*")
        url = f"{self.base_url}/rest/v1/{table}"
        if query_string:
            url = f"{url}?{query_string}"
        request_headers = dict(self.base_headers)
        request_headers.update(headers or {})
        data = None if body is None else json.dumps(body).encode("utf-8")
        request = urllib.request.Request(url, data=data, headers=request_headers, method=method)
        try:
            with urllib.request.urlopen(request, timeout=90, context=self.ssl_context) as response:
                payload = response.read()
        except urllib.error.HTTPError as error:
            detail = error.read().decode("utf-8", errors="replace")
            raise RuntimeError(f"Supabase {method} {table} failed: {error.code} {detail}") from error
        if not payload:
            return None
        return json.loads(payload.decode("utf-8"))


def create_ssl_context() -> ssl.SSLContext:
    default_paths = ssl.get_default_verify_paths()
    if default_paths.cafile and Path(default_paths.cafile).is_file():
        return ssl.create_default_context()
    for candidate in (
        os.environ.get("SSL_CERT_FILE"),
        "/etc/ssl/cert.pem",
        "/opt/homebrew/etc/ca-certificates/cert.pem",
        "/usr/local/etc/openssl@3/cert.pem",
    ):
        if candidate and Path(candidate).is_file():
            return ssl.create_default_context(cafile=candidate)
    return ssl.create_default_context()


def normalize_text(value: str | None) -> str:
    decomposed = unicodedata.normalize("NFD", (value or "").lower())
    without_marks = "".join(char for char in decomposed if not unicodedata.combining(char))
    return re.sub(r"[^a-zñü]+", " ", without_marks).strip()


def normalize_level_band(value: str | None) -> str:
    normalized = normalize_text(value).replace("_", " ").replace("-", " ")
    if "advanced" in normalized:
        return "advanced"
    if "upper" in normalized:
        return "upper intermediate"
    if "lower" in normalized or "intermediate" in normalized:
        return "lower intermediate"
    if "beginner" in normalized or "intro" in normalized:
        return "beginner"
    return "lower intermediate"


def verb_tier(verb_name: str) -> int:
    return COMMON_VERB_TIERS.get(normalize_text(verb_name), 3)


def verb_floor_band(tier: int) -> str:
    if tier <= 1:
        return "beginner"
    if tier == 2:
        return "lower intermediate"
    return "upper intermediate"


def resolve_course_band(candidate: Candidate, judgement: Judgement) -> str:
    levels = [
        normalize_level_band(candidate.db_difficulty),
        normalize_level_band(judgement.estimated_level_band),
        verb_floor_band(candidate.verb_tier),
    ]
    return LEVEL_ORDER[max(LEVEL_INDEX[level] for level in levels)]


def count_words(text: str) -> int:
    return len(re.findall(r"[A-Za-zÁÉÍÓÚÜÑáéíóúüñ]+", text))


def count_proper_noun_guesses(text: str) -> int:
    tokens = re.findall(r"\b[A-ZÁÉÍÓÚÜÑ][A-Za-zÁÉÍÓÚÜÑáéíóúüñ]{2,}\b", text)
    common_sentence_starters = {
        "Pero",
        "Entonces",
        "Porque",
        "Cuando",
        "Como",
        "Esto",
        "Esta",
        "Este",
        "Ahora",
        "Bueno",
        "Claro",
        "También",
        "Sí",
        "No",
    }
    return sum(1 for token in tokens if token not in common_sentence_starters)


def passage_preview(text: str, max_chars: int = 420) -> str:
    compact = re.sub(r"\s+", " ", text).strip()
    if len(compact) <= max_chars:
        return compact
    return compact[: max_chars - 1].rstrip() + "…"


def quality_score(candidate: Candidate, judgement: Judgement) -> float:
    length_penalty = abs(candidate.word_count - 45) / 28
    proper_noun_penalty = max(0, judgement.proper_noun_load - 2) * 1.2
    tier_penalty = (candidate.verb_tier - 1) * 0.45
    count_bonus = math.log(candidate.verb_count + 1) * 0.9
    return round(
        judgement.interest_score * 2.0
        + judgement.clarity_score * 2.1
        + judgement.learner_value_score * 2.2
        + (6 - judgement.proper_noun_load) * 1.4
        + count_bonus
        - length_penalty
        - proper_noun_penalty
        - tier_penalty,
        4,
    )


def cache_key(candidate: Candidate) -> str:
    digest = hashlib.sha256(candidate.passage_text.encode("utf-8")).hexdigest()[:16]
    return f"{candidate.top_verb_video_id}:{digest}"


def judgement_schema() -> dict[str, Any]:
    return {
        "type": "object",
        "additionalProperties": False,
        "properties": {
            "eligible": {"type": "boolean"},
            "interest_score": {"type": "integer", "minimum": 1, "maximum": 5},
            "clarity_score": {"type": "integer", "minimum": 1, "maximum": 5},
            "proper_noun_load": {"type": "integer", "minimum": 1, "maximum": 5},
            "learner_value_score": {"type": "integer", "minimum": 1, "maximum": 5},
            "estimated_level_band": {
                "type": "string",
                "enum": LEVEL_ORDER,
            },
            "estimated_cefr": {
                "type": "string",
                "enum": ["A1", "A2", "B1", "B2", "C1", "C2"],
            },
            "rejection_reason": {"type": "string"},
            "short_rationale": {"type": "string"},
        },
        "required": [
            "eligible",
            "interest_score",
            "clarity_score",
            "proper_noun_load",
            "learner_value_score",
            "estimated_level_band",
            "estimated_cefr",
            "rejection_reason",
            "short_rationale",
        ],
    }


def extract_response_text(payload: dict[str, Any]) -> str:
    if isinstance(payload.get("output_text"), str):
        return payload["output_text"]
    for output in payload.get("output", []):
        for content in output.get("content", []):
            text = content.get("text")
            if isinstance(text, str):
                return text
    raise RuntimeError(f"Could not find text in OpenAI response: {payload}")


def call_openai_judge(candidate: Candidate, *, model: str, api_key: str) -> Judgement:
    passage_text = candidate.passage_text
    if len(passage_text) > MAX_MODEL_TEXT_CHARS:
        passage_text = passage_text[: MAX_MODEL_TEXT_CHARS - 1].rstrip() + "…"

    prompt_payload = {
        "verb": candidate.verb,
        "verb_tier": candidate.verb_tier,
        "verb_form_count": candidate.verb_count,
        "database_difficulty": candidate.db_difficulty,
        "word_count": candidate.word_count,
        "proper_noun_guess_count": candidate.proper_noun_guess_count,
        "video_title": candidate.video_title,
        "passage_text": passage_text,
    }
    request_payload = {
        "model": model,
        "input": [
            {
                "role": "system",
                "content": [
                    {
                        "type": "input_text",
                        "text": (
                            "You judge Spanish transcript passages for a guided language-learning course. "
                            "Prefer clear, interesting, self-contained everyday Spanish. Penalize passages "
                            "with many proper nouns, list-like fragments, transcript noise, mostly English, "
                            "or context that is hard to understand alone. Estimate learner level from the "
                            "passage itself, while considering the focused verb."
                        ),
                    }
                ],
            },
            {
                "role": "user",
                "content": [{"type": "input_text", "text": json.dumps(prompt_payload, ensure_ascii=False)}],
            },
        ],
        "text": {
            "format": {
                "type": "json_schema",
                "name": "guided_passage_judgement",
                "strict": True,
                "schema": judgement_schema(),
            }
        },
    }
    data = json.dumps(request_payload).encode("utf-8")
    request = urllib.request.Request(
        "https://api.openai.com/v1/responses",
        data=data,
        method="POST",
        headers={
            "Authorization": f"Bearer {api_key}",
            "Content-Type": "application/json",
        },
    )
    for attempt in range(4):
        try:
            with urllib.request.urlopen(request, timeout=90, context=create_ssl_context()) as response:
                payload = json.loads(response.read().decode("utf-8"))
            return parse_judgement(json.loads(extract_response_text(payload)))
        except urllib.error.HTTPError as error:
            detail = error.read().decode("utf-8", errors="replace")
            if error.code not in {429, 500, 502, 503, 504} or attempt == 3:
                raise RuntimeError(f"OpenAI request failed: {error.code} {detail}") from error
        except Exception:
            if attempt == 3:
                raise
        time.sleep(2**attempt)
    raise RuntimeError("OpenAI judgement failed")


def parse_judgement(value: dict[str, Any]) -> Judgement:
    return Judgement(
        eligible=bool(value.get("eligible")),
        interest_score=clamp_int(value.get("interest_score"), 1, 5),
        clarity_score=clamp_int(value.get("clarity_score"), 1, 5),
        proper_noun_load=clamp_int(value.get("proper_noun_load"), 1, 5),
        learner_value_score=clamp_int(value.get("learner_value_score"), 1, 5),
        estimated_level_band=normalize_level_band(str(value.get("estimated_level_band") or "")),
        estimated_cefr=str(value.get("estimated_cefr") or "B1"),
        rejection_reason=str(value.get("rejection_reason") or ""),
        short_rationale=str(value.get("short_rationale") or ""),
    )


def clamp_int(value: Any, minimum: int, maximum: int) -> int:
    try:
        parsed = int(value)
    except (TypeError, ValueError):
        parsed = minimum
    return max(minimum, min(maximum, parsed))


def load_env_file(path: Path) -> None:
    for raw_line in path.read_text(encoding="utf-8").splitlines():
        line = raw_line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        os.environ.setdefault(key.strip(), value.strip().strip("'").strip('"'))


def candidate_env_paths(repo_root: Path, explicit_path: str | None) -> Iterable[Path]:
    if explicit_path:
        yield Path(explicit_path).expanduser()
    for base in [Path.cwd(), repo_root, *repo_root.parents]:
        yield base / ".env"
    try:
        result = subprocess.run(
            ["git", "worktree", "list", "--porcelain"],
            cwd=repo_root,
            check=False,
            stdout=subprocess.PIPE,
            stderr=subprocess.DEVNULL,
            text=True,
        )
    except OSError:
        return
    for line in result.stdout.splitlines():
        if line.startswith("worktree "):
            yield Path(line.removeprefix("worktree ")).expanduser() / ".env"


def load_environment(repo_root: Path, explicit_env_file: str | None) -> Path | None:
    seen: set[Path] = set()
    for env_path in candidate_env_paths(repo_root, explicit_env_file):
        if env_path in seen:
            continue
        seen.add(env_path)
        if env_path.is_file():
            load_env_file(env_path)
            return env_path
    return None


def chunked(items: list[Any], chunk_size: int) -> Iterable[list[Any]]:
    for start in range(0, len(items), chunk_size):
        yield items[start : start + chunk_size]


def create_tables(db_url: str) -> None:
    psql = shutil.which("psql")
    if not psql:
        raise RuntimeError("psql is required to create guided-learning tables automatically.")
    subprocess.run([psql, db_url, "-v", "ON_ERROR_STOP=1", "-c", CREATE_TABLES_SQL], check=True)


def load_rows(client: SupabaseRestClient, language: str, segment_chunk_size: int) -> list[Candidate]:
    verbs = {
        row["id"]: Verb(id=row["id"], name=str(row.get("name") or ""))
        for row in client.fetch_all("verb", select="id,name")
    }
    channels = {
        str(row.get("channel_id") or ""): Channel(
            channel_id=str(row.get("channel_id") or ""),
            difficulty=row.get("difficulty"),
            language=row.get("language"),
        )
        for row in client.fetch_all("channel", select="channel_id,difficulty,language")
    }
    videos = {
        row["id"]: Video(
            id=row["id"],
            video_id=row.get("video_id"),
            channel_id=str(row.get("channel_id") or ""),
            difficulty=row.get("difficulty"),
            title=row.get("title"),
        )
        for row in client.fetch_all("video", select="id,video_id,channel_id,difficulty,title")
    }
    top_rows = [
        TopVerbVideo(
            id=row["id"],
            video_id=row.get("video_id"),
            verb_id=row.get("verb_id"),
            count=int(row.get("count") or 0),
            difficulty=row.get("difficulty"),
            start=int(row.get("start") or 0),
            end=int(row.get("end") or row.get("start") or 0),
        )
        for row in client.fetch_all("top_verb_video", select="id,video_id,verb_id,count,difficulty,start,end")
        if row.get("video_id") is not None and row.get("verb_id") is not None
    ]
    video_ids = sorted({row.video_id for row in top_rows}, key=lambda value: str(value))
    segments_by_video_id: dict[str, list[Segment]] = {}
    for chunk in chunked(video_ids, segment_chunk_size):
        in_filter = ",".join(str(video_id) for video_id in chunk)
        rows = client.fetch_all(
            "transcript_segment",
            select="segment_id,text,video_id",
            filters={"video_id": f"in.({in_filter})"},
            order="video_id.asc,segment_id.asc",
        )
        for row in rows:
            text = str(row.get("text") or "").strip()
            if not text:
                continue
            segment = Segment(
                segment_id=int(row.get("segment_id") or 0),
                text=text,
                video_id=row.get("video_id"),
            )
            segments_by_video_id.setdefault(str(row.get("video_id")), []).append(segment)

    candidates: list[Candidate] = []
    for row in top_rows:
        video = videos.get(row.video_id)
        verb = verbs.get(row.verb_id)
        if not video or not verb:
            continue
        channel = channels.get(video.channel_id)
        if channel and channel.language != language:
            continue
        segments = [
            segment
            for segment in segments_by_video_id.get(str(row.video_id), [])
            if row.start <= segment.segment_id <= row.end
        ]
        text = " ".join(segment.text for segment in segments).strip()
        if not text:
            continue
        tier = verb_tier(verb.name)
        candidates.append(
            Candidate(
                top_verb_video_id=row.id,
                video_id=row.video_id,
                verb_id=row.verb_id,
                verb=verb.name,
                verb_tier=tier,
                verb_count=row.count,
                video_title=video.title or "",
                db_difficulty=row.difficulty or video.difficulty or channel.difficulty if channel else row.difficulty or video.difficulty or "",
                start_segment_id=row.start,
                end_segment_id=row.end,
                passage_text=text,
                passage_preview=passage_preview(text),
                word_count=count_words(text),
                proper_noun_guess_count=count_proper_noun_guesses(text),
            )
        )
    return candidates


def load_judgement_cache(path: Path) -> dict[str, Judgement]:
    if not path.is_file():
        return {}
    cache: dict[str, Judgement] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip():
            continue
        record = json.loads(line)
        cache[str(record["cache_key"])] = parse_judgement(record["judgement"])
    return cache


def append_judgement_cache(path: Path, key: str, judgement: Judgement) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("a", encoding="utf-8") as handle:
        handle.write(json.dumps({"cache_key": key, "judgement": asdict(judgement)}, ensure_ascii=False) + "\n")


def judge_candidates(
    candidates: list[Candidate],
    *,
    model: str,
    api_key: str,
    cache_path: Path,
    rejudge: bool,
    limit: int | None,
) -> list[JudgedCandidate]:
    cached = {} if rejudge else load_judgement_cache(cache_path)
    judged: list[JudgedCandidate] = []
    working_candidates = candidates[: limit or len(candidates)]
    for index, candidate in enumerate(working_candidates, start=1):
        key = cache_key(candidate)
        judgement = cached.get(key)
        if not judgement:
            LOGGER.info("[%s/%s] judging %s (%s)", index, len(working_candidates), candidate.verb, candidate.top_verb_video_id)
            judgement = call_openai_judge(candidate, model=model, api_key=api_key)
            append_judgement_cache(cache_path, key, judgement)
        course_band = resolve_course_band(candidate, judgement)
        judged.append(
            JudgedCandidate(
                candidate=candidate,
                judgement=judgement,
                course_band=course_band,
                quality_score=quality_score(candidate, judgement),
            )
        )
    return judged


def candidate_sort_key(item: JudgedCandidate) -> tuple[Any, ...]:
    candidate = item.candidate
    return (
        -item.quality_score,
        candidate.verb_tier,
        -candidate.verb_count,
        candidate.proper_noun_guess_count,
        candidate.word_count,
        str(candidate.top_verb_video_id),
    )


def select_course_passages(
    judged: list[JudgedCandidate],
    *,
    targets: dict[str, int] | None = None,
    max_per_verb: int = MAX_PASSAGES_PER_VERB,
    max_per_video: int = MAX_PASSAGES_PER_VIDEO,
) -> list[JudgedCandidate]:
    targets = targets or COURSE_TARGETS
    selected: list[JudgedCandidate] = []
    selected_keys: set[str] = set()
    verb_counts: dict[str, int] = {}
    video_counts: dict[str, int] = {}
    eligible = [
        item
        for item in judged
        if item.judgement.eligible
        and item.candidate.word_count >= 8
        and item.candidate.word_count <= 140
        and item.judgement.clarity_score >= 3
        and item.judgement.learner_value_score >= 3
        and item.judgement.proper_noun_load <= 4
    ]

    for band in LEVEL_ORDER:
        pool = sorted([item for item in eligible if item.course_band == band], key=candidate_sort_key)
        needed = targets.get(band, 0)
        add_from_pool(
            pool,
            selected,
            selected_keys,
            verb_counts,
            video_counts,
            needed,
            max_per_verb=max_per_verb,
            max_per_video=max_per_video,
        )

    if len(selected) < sum(targets.values()):
        pool = sorted(eligible, key=candidate_sort_key)
        add_from_pool(
            pool,
            selected,
            selected_keys,
            verb_counts,
            video_counts,
            sum(targets.values()) - len(selected),
            max_per_verb=max_per_verb + 4,
            max_per_video=max_per_video + 2,
        )

    return interleave_course(selected[: sum(targets.values())])


def add_from_pool(
    pool: list[JudgedCandidate],
    selected: list[JudgedCandidate],
    selected_keys: set[str],
    verb_counts: dict[str, int],
    video_counts: dict[str, int],
    needed: int,
    *,
    max_per_verb: int,
    max_per_video: int,
) -> None:
    added = 0
    for item in pool:
        key = str(item.candidate.top_verb_video_id)
        verb_key = normalize_text(item.candidate.verb)
        video_key = str(item.candidate.video_id)
        if key in selected_keys:
            continue
        if verb_counts.get(verb_key, 0) >= max_per_verb:
            continue
        if video_counts.get(video_key, 0) >= max_per_video:
            continue
        selected.append(item)
        selected_keys.add(key)
        verb_counts[verb_key] = verb_counts.get(verb_key, 0) + 1
        video_counts[video_key] = video_counts.get(video_key, 0) + 1
        added += 1
        if added >= needed:
            return


def interleave_course(items: list[JudgedCandidate]) -> list[JudgedCandidate]:
    by_band = {band: sorted([item for item in items if item.course_band == band], key=candidate_sort_key) for band in LEVEL_ORDER}
    ordered: list[JudgedCandidate] = []
    for band in LEVEL_ORDER:
        ordered.extend(by_band[band])
    for index in range(1, len(ordered)):
        current = ordered[index]
        previous = ordered[index - 1]
        if (
            current.candidate.verb == previous.candidate.verb
            or str(current.candidate.video_id) == str(previous.candidate.video_id)
        ):
            swap_index = next(
                (
                    later
                    for later in range(index + 1, len(ordered))
                    if ordered[later].candidate.verb != previous.candidate.verb
                    and str(ordered[later].candidate.video_id) != str(previous.candidate.video_id)
                ),
                None,
            )
            if swap_index is not None:
                ordered[index], ordered[swap_index] = ordered[swap_index], ordered[index]
    return ordered


def course_rows(selected: list[JudgedCandidate], *, model: str, language: str) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for rank, item in enumerate(selected, start=1):
        candidate = item.candidate
        judgement = item.judgement
        rows.append(
            {
                "language": language,
                "top_verb_video_id": candidate.top_verb_video_id,
                "video_id": candidate.video_id,
                "verb_id": candidate.verb_id,
                "level_band": item.course_band,
                "rank_order": rank,
                "skill_focus": "verb forms",
                "start_segment_id": candidate.start_segment_id,
                "end_segment_id": candidate.end_segment_id,
                "quality_score": item.quality_score,
                "interest_score": judgement.interest_score,
                "clarity_score": judgement.clarity_score,
                "proper_noun_load": judgement.proper_noun_load,
                "learner_value_score": judgement.learner_value_score,
                "estimated_cefr": judgement.estimated_cefr,
                "verb_tier": candidate.verb_tier,
                "word_count": candidate.word_count,
                "passage_preview": candidate.passage_preview,
                "evaluator_model": model,
                "evaluator_json": asdict(judgement),
            }
        )
    return rows


def write_course(client: SupabaseRestClient, rows: list[dict[str, Any]], *, language: str) -> None:
    client.delete("learning_passage", filters={"language": f"eq.{language}"})
    client.insert("learning_passage", rows)


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Judge top_verb_video passages and populate the curated Spanish learning_passage course.",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument("--env-file", help="Explicit .env file to load.")
    parser.add_argument("--model", default=os.environ.get("OPENAI_GUIDED_PASSAGE_MODEL", DEFAULT_MODEL))
    parser.add_argument("--language", default=DEFAULT_LANGUAGE)
    parser.add_argument("--cache-file", default=".cache/guided-learning-judgements.jsonl")
    parser.add_argument("--limit", type=int, help="Judge only this many candidates.")
    parser.add_argument("--dry-run", action="store_true", help="Do not write learning_passage rows.")
    parser.add_argument("--write", action="store_true", help="Write selected rows to learning_passage.")
    parser.add_argument("--resume", action="store_true", default=True, help="Reuse cached judgements.")
    parser.add_argument("--rejudge", action="store_true", help="Ignore cached judgements and call OpenAI again.")
    parser.add_argument("--create-tables", action="store_true", help="Create learning_passage/progress tables before writing.")
    parser.add_argument("--print-create-sql", action="store_true", help="Print the table creation SQL and exit.")
    parser.add_argument("--page-size", type=int, default=DEFAULT_PAGE_SIZE)
    parser.add_argument("--segment-video-chunk-size", type=int, default=DEFAULT_SEGMENT_VIDEO_CHUNK_SIZE)
    return parser.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    logging.basicConfig(level=logging.INFO, format="%(levelname)s: %(message)s")
    repo_root = Path(__file__).resolve().parents[1]
    env_path = load_environment(repo_root, args.env_file)
    if env_path:
        LOGGER.info("Loaded environment from %s", env_path)
    if args.print_create_sql:
        print(CREATE_TABLES_SQL.strip())
        return 0

    supabase_url = os.environ.get("EXPO_PUBLIC_SUPABASE_URL")
    service_role_key = os.environ.get("SUPABASE_SERVICE_ROLE_KEY")
    openai_api_key = os.environ.get("OPENAI_API_KEY")
    db_url = os.environ.get("SUPABASE_DB_URL") or os.environ.get("DATABASE_URL")
    if not supabase_url or not service_role_key:
        raise SystemExit("Missing EXPO_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY.")
    if not openai_api_key:
        raise SystemExit("Missing OPENAI_API_KEY.")
    if args.create_tables:
        if not db_url:
            raise SystemExit("Missing SUPABASE_DB_URL or DATABASE_URL for --create-tables.")
        create_tables(db_url)
    if args.write and args.dry_run:
        raise SystemExit("Use either --write or --dry-run, not both.")
    if not args.write and not args.dry_run:
        raise SystemExit("Choose --dry-run or --write.")

    client = SupabaseRestClient(supabase_url, service_role_key, args.page_size)
    candidates = load_rows(client, args.language, args.segment_video_chunk_size)
    LOGGER.info("Loaded %s candidate passage(s).", len(candidates))
    judged = judge_candidates(
        candidates,
        model=args.model,
        api_key=openai_api_key,
        cache_path=Path(args.cache_file),
        rejudge=args.rejudge,
        limit=args.limit,
    )
    selected = select_course_passages(judged)
    rows = course_rows(selected, model=args.model, language=args.language)
    band_counts: dict[str, int] = {}
    for row in rows:
        band_counts[row["level_band"]] = band_counts.get(row["level_band"], 0) + 1
    LOGGER.info("Selected %s passage(s): %s", len(rows), band_counts)
    if args.dry_run:
        print(json.dumps(rows[:10], ensure_ascii=False, indent=2))
        return 0
    write_course(client, rows, language=args.language)
    LOGGER.info("Wrote %s learning_passage row(s).", len(rows))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
